Pull Request from Sam Gresh @ NACHC- Downloadable exe
mitre/data-owner-tools pull request #4
Opened 2021-05-03 18:10 UTC by Sam-Gresh

Pyinstaller package for one-file executable for garble.py and linkidtopatid.py.

2021-05-17 14:32 UTC, eedrummer requested changes
Hi Sam,

Thanks for the PR. Overall, it looks good. A few key things to change before I can merge this in:

* Please remove the `.idea` directory from the PR
* Field names in the WxPython based classes should be descriptive 
* Please add to the README, don't overwrite the existing contents

2021-05-17 14:32 UTC, eedrummer commented on .idea/.gitignore
> +# Default ignored files
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/data-owner-tools.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/deployment.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be checked in

2021-05-17 14:32 UTC, eedrummer commented on GarbleExecutable.py
> +        self.txt2 = None
This line is a repeat of line 23

2021-05-17 14:32 UTC, eedrummer commented on GarbleExecutable.py
> +        self.txt1 = None
Field names should be more descriptive than `txt1`. This could be `self.csv_file_location`

2021-05-17 14:32 UTC, eedrummer commented on Link-IDs-Executable.py
> +        self.txt1 = None
Same comment as before. Please chose more descriptive names for the fields.

2021-05-17 14:32 UTC, eedrummer commented on README.md
> +# Data Owner Tools Executables
This change overwrites the existing README file. These should be added to the README instead.

2021-05-17 14:32 UTC, eedrummer commented on README.md
> +To use the garble tool, download GarbleExecutable.exe from: https://github.com/Sam-Gresh/data-owner-tools/releases/tag/v0.0.3. Optionally, create an output directory. Run the executable. Select the P
`GarbleExecutable.exe` assumes that the user will be running Windows. That's most likely the case, but we should at least mention that in the text and provide something for macOS and linux users.

2021-05-17 14:32 UTC, eedrummer commented on secret-file/secret-file.txt
> +=kl:2Eh9F!4tg1xlDlpknpCcG-JIqy:eSXDZnJtbx6KW6nL+:HkmkjLJ!*A#.5nw0qZn_olt0J+byJKM8qzf5Vbpb#I4@Rw?RefFExZ1Ar?_@LyCeZ-QRLzsg0BaDktol2qvLcqGM5/SantGA/M5)*_5ZBoRNg)WATXc@AKD4@qbvX)/YEX.eX9!.hjcU6:#FBvXFEM
This file should not be checked in

2021-05-17 19:34 UTC, Sam-Gresh commented
Hi Andy,
Quick question about the garble executable. Right now the tool includes the
secret file as part of the built executable. Should the secret file instead
be selected by the user?
-Sam Gresh

On Mon, May 17, 2021 at 10:32 AM Andy Gregorowicz ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi Sam,
>
> Thanks for the PR. Overall, it looks good. A few key things to change
> before I can merge this in:
>
>    - Please remove the .idea directory from the PR
>    - Field names in the WxPython based classes should be descriptive
>    - Please add to the README, don't overwrite the existing contents
>
> ------------------------------
>
> In .idea/.gitignore
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633571617>:
>
> > @@ -0,0 +1,8 @@
> +# Default ignored files
>
> This file should not be checked in
> ------------------------------
>
> In .idea/data-owner-tools.iml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633571716>:
>
> > @@ -0,0 +1,10 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> This file should not be checked in
> ------------------------------
>
> In .idea/deployment.xml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633571834>:
>
> > @@ -0,0 +1,21 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> This file should not be checked in
> ------------------------------
>
> In .idea/inspectionProfiles/Project_Default.xml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633571929>:
>
> > @@ -0,0 +1,54 @@
> +<component name="InspectionProjectProfileManager">
>
> This file should not be checked in
> ------------------------------
>
> In .idea/inspectionProfiles/profiles_settings.xml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633572045>:
>
> > @@ -0,0 +1,6 @@
> +<component name="InspectionProjectProfileManager">
>
> This file should not be checked in
> ------------------------------
>
> In .idea/misc.xml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633572147>:
>
> > @@ -0,0 +1,7 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> This file should not be checked in
> ------------------------------
>
> In .idea/modules.xml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633572227>:
>
> > @@ -0,0 +1,8 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> This file should not be checked in
> ------------------------------
>
> In .idea/vcs.xml
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633572315>:
>
> > @@ -0,0 +1,6 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> This file should not be checked in
> ------------------------------
>
> In GarbleExecutable.py
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633572733>:
>
> > +
> +if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
> +    os.chdir(sys._MEIPASS)
> +
> +
> +class CSVManager(wx.Frame):
> +    def __init__(self, *args, **kwargs):
> +        super(CSVManager, self).__init__(*args, **kwargs)
> +        self.PII_path = ""
> +        self.output_dir = ""
> +        self.schema_dir = "example-schema"
> +        self.salt_path = "secret-file/secret-file.txt"
> +        self.txt1 = None
> +        self.txt2 = None
> +        self.txt3 = None
> +        self.txt2 = None
>
> This line is a repeat of line 23
> ------------------------------
>
> In GarbleExecutable.py
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633573864>:
>
> > +
> +#pyinstaller GarbleExecutable.py  --onefile -w --add-data ./venv/Lib/site-packages/clkhash/data;clkhash/data --add-data ./venv/Lib/site-packages/clkhash/schemas;clkhash/schemas --add-data ./example-schema;example-schema --add-data ./secret-file/secret-file.txt;secret-file
> +
> +
> +if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
> +    os.chdir(sys._MEIPASS)
> +
> +
> +class CSVManager(wx.Frame):
> +    def __init__(self, *args, **kwargs):
> +        super(CSVManager, self).__init__(*args, **kwargs)
> +        self.PII_path = ""
> +        self.output_dir = ""
> +        self.schema_dir = "example-schema"
> +        self.salt_path = "secret-file/secret-file.txt"
> +        self.txt1 = None
>
> Field names should be more descriptive than txt1. This could be
> self.csv_file_location
> ------------------------------
>
> In Link-IDs-Executable.py
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633575033>:
>
> > +import sys
> +import os
> +
> +#pyinstaller Link-IDs-Executable.py --onefile -w
> +
> +if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
> +    os.chdir(sys._MEIPASS)
> +
> +
> +class CSVManager(wx.Frame):
> +    def __init__(self, *args, **kwargs):
> +        super(CSVManager, self).__init__(*args, **kwargs)
> +        self.PII_path = ""
> +        self.link_ids_path = ""
> +        self.output_dir = ""
> +        self.txt1 = None
>
> Same comment as before. Please chose more descriptive names for the fields.
> ------------------------------
>
> In README.md
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633576344>:
>
> > -
> -When anonlink matches across data owners / partners, it identifies records by their position in the file. It essentially uses the line number in the extracted PII file as the identifier for the record. When results are returned from the DCC, it will assign a LINK_ID to a line number in the PII CSV file.
> -
> -To map the LINK_IDs back to PATIDs, use the `linkidtopatid.py` script. The script takes two arguments:
> -
> -1. The path to the PII CSV file
> -1. THe path to the LINK_ID CSV file provided by the DCC
> -
> -The script will create a file called `linkidtopatid.csv` with the mapping of LINK_IDs to PATIDs.
> -
> -## Notice
> -
> -Copyright 2020 The MITRE Corporation.
> -
> -Approved for Public Release; Distribution Unlimited. Case Number 19-2008
> +# Data Owner Tools Executables
>
> This change overwrites the existing README file. These should be added to
> the README instead.
> ------------------------------
>
> In README.md
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633577747>:
>
> > -
> -1. The path to the PII CSV file
> -1. THe path to the LINK_ID CSV file provided by the DCC
> -
> -The script will create a file called `linkidtopatid.csv` with the mapping of LINK_IDs to PATIDs.
> -
> -## Notice
> -
> -Copyright 2020 The MITRE Corporation.
> -
> -Approved for Public Release; Distribution Unlimited. Case Number 19-2008
> +# Data Owner Tools Executables
> +Fork of https://github.com/mitre/data-owner-tools. All python files should conform to existing command line documentation. Command line and GUI tools should be interoperable. Executables built using pyinstaller version 4.2.
> +
> +## Basic End User Instructions:
> +To use the garble tool, download GarbleExecutable.exe from: https://github.com/Sam-Gresh/data-owner-tools/releases/tag/v0.0.3. Optionally, create an output directory. Run the executable. Select the PII csv file, and the output directory, then click the Garble button. The garbled files will be created in the output directory.
>
> GarbleExecutable.exe assumes that the user will be running Windows.
> That's most likely the case, but we should at least mention that in the
> text and provide something for macOS and linux users.
> ------------------------------
>
> In secret-file/secret-file.txt
> <https://github.com/mitre/data-owner-tools/pull/4#discussion_r633582586>:
>
> > @@ -0,0 +1 @@
> +=kl:2Eh9F!4tg1xlDlpknpCcG-JIqy:eSXDZnJtbx6KW6nL+:HkmkjLJ!*A#.5nw0qZn_olt0J+byJKM8qzf5Vbpb#I4@Rw?RefFExZ1Ar?_@LyCeZ-QRLzsg0BaDktol2qvLcqGM5/SantGA/M5)*_5ZBoRNg)WATXc@***@***.***X)/YEX.eX9!.hjcU6:#FBvXFEM:ptvmf0PiIhLaP=j!jY0!t6L5l:(B/O)q=mctbBk8oNdD#V1R9zcvF8BzA/Y!Nppa#J*djGbv_E1zqK(g=yMxN8sOSoHLMxc:mXlnVU)Qo*#!!NS)WYb/AkfAeCVBjWI6s)+(Zek!(_O0=2:s@***@***.******@***.******@***.******@***.***#-hxMguj(/t!UKYwMOiZ=9.puBJ7!W
>
> This file should not be checked in
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, vie [...]

2021-06-16 17:23 UTC, eedrummer requested changes
This looks really close. In addition to the minor comments in the review, can you please remove the `all_patients.csv` and `fhir_pii.csv` files from the PR.

2021-06-16 17:23 UTC, eedrummer commented on README.md
> +# Data Owner Tools Executables
This can go above the notice section

2021-06-16 17:23 UTC, eedrummer commented on README.md
> +Fork of https://github.com/mitre/data-owner-tools. All python files should conform to existing command line documentation. Command line and GUI tools should be interoperable. Executables built using
Please remove the text about this being a fork. When we merge it in, it will just be in the repo.

2021-07-19 20:12 UTC, eedrummer commented
Hey @Sam-Gresh! I didn't forget about you.

First, the good news. I was able to get the `Link-IDs-Executable.py` to build on macOS:

<img width="962" alt="Screen Shot 2021-07-19 at 4 05 08 PM" src="https://user-images.githubusercontent.com/17500/126220506-280d671b-a042-444c-bcd5-4e3226756eb6.png">

Now, the not so good news. While I could get `GarbleExecutable.py` to build, I couldn't get the app to run. In troubleshooting, I noticed that the current readme says that the salt is supposed to get compiled into the app. Reading the actual code leads me to believe that is not true. Can you update the readme? Particularly the `pyinstaller` part. I suspect that I need one of the `--add-data` arguments, but what is in the docs is out of date.

2021-07-21 17:00 UTC, Sam-Gresh commented
Hi @eedrummer, 
It was indeed the --add-data parameter causing the problem. Not only is the secret file no longer included, but I had forgotten that the paths were relative to the venv. I have now included instructions for creating a venv. Additionally there are some differences between the way venv creates directories on Windows and Linux. Also the ";" in the add-data parameter must be replaced with ":" on Linux. I have separated out the build instructions for Linux and Windows in the readme. I have successfully gotten both executables to compile in a Linux VM. Though I do not have a Mac to test on, I suspect that the Mac system is consistent with the Linux instructions.

2021-08-02 15:20 UTC, eedrummer approved these changes

2021-09-03 17:51 UTC, closed without merging